[project]
name = "metaexpert-binance-api"
version = "0.1.0"
description = "MetaExpert driver for Binance API"
authors = [{ name = "Oleg Alexandrov", email = "alexandrovoleg.ru@gmail.com" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "binance-connector>=3.12.0",
]

[tool.uv]
package = false
